# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lPixmap = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lPixmap.sizePolicy().hasHeightForWidth())
        self.lPixmap.setSizePolicy(sizePolicy)
        self.lPixmap.setText("")
        self.lPixmap.setObjectName("lPixmap")
        self.verticalLayout_2.addWidget(self.lPixmap)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(110, 208))
        self.dockWidget.setFloating(False)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.comboBox_AttractorType = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_AttractorType.setObjectName("comboBox_AttractorType")
        self.verticalLayout_4.addWidget(self.comboBox_AttractorType)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.spinBox_NumberOfIterations = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_NumberOfIterations.setMinimumSize(QtCore.QSize(0, 20))
        self.spinBox_NumberOfIterations.setMaximum(10000000000000)
        self.spinBox_NumberOfIterations.setSingleStep(1000000)
        self.spinBox_NumberOfIterations.setProperty("value", 0)
        self.spinBox_NumberOfIterations.setObjectName("spinBox_NumberOfIterations")
        self.verticalLayout_5.addWidget(self.spinBox_NumberOfIterations)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.comboBox_AxialOrientation = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_AxialOrientation.setObjectName("comboBox_AxialOrientation")
        self.verticalLayout_6.addWidget(self.comboBox_AxialOrientation)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.comboBox_cmaps = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_cmaps.setObjectName("comboBox_cmaps")
        self.verticalLayout_7.addWidget(self.comboBox_cmaps)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.pushButton_Plot = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_Plot.setObjectName("pushButton_Plot")
        self.verticalLayout_8.addWidget(self.pushButton_Plot)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_Save_Attractor = QtWidgets.QAction(MainWindow)
        self.action_Save_Attractor.setObjectName("action_Save_Attractor")
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.action_Save_Attractor)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Strange Attractors Demo"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Options"))
        self.label.setText(_translate("MainWindow", "Attractor Type:"))
        self.label_2.setText(_translate("MainWindow", "Number of Iterations:"))
        self.label_4.setText(_translate("MainWindow", "Axial Orientation:"))
        self.label_3.setText(_translate("MainWindow", "Color Map:"))
        self.pushButton_Plot.setText(_translate("MainWindow", "Plot"))
        self.actionLoad_File.setText(_translate("MainWindow", "&Load File"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.action_Save_Attractor.setText(_translate("MainWindow", "&Save Image"))

import resources_rc
